[build]
publish = "_site"
command = 'jekyll build --baseurl="$DEPLOY_PRIME_URL"'

[build.environment]
RUBY_VERSION = "2.6.3"

[context.production]
command = "jekyll build"

[[redirects]]
from = "/*"
to = "/404.html"
status = 404
